// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloWorld.proto

package com.skc.grpc.helloworld;

public interface GreetingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skc.grpc.helloworld.Greeting)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
